spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/fullstack_auth
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

liquibase:
  change-log: db/changelog/liquibase-changeLog.xml
  enabled: true
